---
title: "Patrick Cherry"
format: gfm
---
:::{.callout-note}
## I am hiring.
Hi everyone, I am hiring for a Research Associate to join the BillionToOne Research and Development team in Menlo Park to help work on making our Oncology tests more sensitive and broader in scope. I am looking for a BS or MS in Molecular / Cell Biology or related fields with 1-2 years research experience in standard molecular biology techniques, and the ability to quickly learn experimental, mathematical, and statistical concepts. BillionToOne can offer interesting and impactful work, great coworkers, and great benefits. Apply using the link below, or DM me to recommend someone you think would be a good fit.

[Job Post | Research Associate | BillionToOne | Core Development, Oncology](https://grnh.se/0541b3175us)
:::

### Experience
 - BillionToOne | Senior Scientist, Oncology R&D | Sept. 2024 - Current
 - Twist Bioscience | Senior R&D Scientist | Jan. 2021 - Apr. 2024
 - Zymergen | NGS Scientist | May 2019 - Dec. 2020

### Résumé and CV
 - [View CV in browser](https://pdcherry.github.io/Patrick-Cherry-cv.html)
 - [Download resume as pdf](https://pdcherry.github.io/Patrick-Cherry-resume.pdf)
 - [Resume and CV git repo](https://github.com/pdcherry/cherry-cv-public)

### Education
 - PhD in Molecular Biology | University of Colorado Anschutz Medical Campus
 - B.A. in Biochemistry and Molecular Biology | Hendrix College

### Bio
Patrick invents products and procedures for manipulating DNA, RNA, and their sequence information in novel and helpful ways. He focuses on writing reproducible bioinformatic analysis pipelines that cater to users of all levels. Patrick is known for inventing the Twist Pan-cancer Reference Standards (v1 & v2), the Fragmentome Calibration Control, and the RNA Fusion Positive Control.

### Interests
Patrick is a PhD scientist skilled in bioinformatics, biological data science, data visualization, statistical modeling, next-generation sequencing (NGS), and tool-building. Patrick has coded reproducible and rigorous pipelines for high-throughput experimental designs and genomic analyses, launched best-in-class oncology reference standards, and invented new molecular methods for DNA and microbe manipulation. Originally trained in Molecular Biology, Patrick is interested in taking his knowledge and practice of data science / bioinformatics to the next level.

### Miscellaneous
Patrick is an avid outdoorsman and indoorsman. Outdoor pursuits include rock climbing, skiing, trail running, and landscape photography. Indoor hobbies include table top games, cooking, baking, photographic printing / framing / design.